### ISSUE TITLE
Crash on opening card

### ISSUE THREAD

**Issue by StraDijk** [gruijter/com.plugwise.smile#1]
The app crashes on opening card and gives the following stack trace:

`TypeError: Cannot read property '0' of undefined
at storeNewReadings (/drivers/smilep1/driver.js:380:66)
at /drivers/smilep1/driver.js:330:17
at Parser.<anonymous> (/node_modules/xml2js/lib/xml2js.js:484:18)
at emitOne (events.js:77:13)
at Parser.emit (events.js:169:7)
at Object.onclosetag (/node_modules/xml2js/lib/xml2js.js:445:26)
at emit (/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
at emitNode (/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
at closeTag (/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)
at Object.write (/node_modules/xml2js/node_modules/sax/lib/sax.js:1449:13)

Exit code: 1
Exit signal: null`

**Comment by gruijter** [comment]
New version 1.0 should resolve the issue

**Comment by StraDijk** [comment]
```
<modules>
<module id="e01c4092a7b54a4aaa8198b2eeb9dabe">
<vendor_name/>
<vendor_model/>
<hardware_version/>
<firmware_version/>
<created_date>2016-11-26T16:38:30.163+01:00</created_date>
<modified_date>2016-11-26T20:10:48.365+01:00</modified_date>
<deleted_date/>
<services>
<gas_interval_meter id="130c96e511ae43f09572533726271d9b">
<measurement log_date="2016-11-26T18:00:00+01:00" unit="m3" interval="PT1H" directionality="consumed">0.000</measurement>
</gas_interval_meter>
<gas_cumulative_meter id="4926948517c348f9bdbd8c146c8680cc">
<measurement log_date="2016-11-26T19:00:00+01:00" unit="m3" directionality="consumed">2096.348</measurement>
</gas_cumulative_meter>
</services>
<protocols>
<dsmrgas id="cd27a7eb09904168a5d43ae5c0ec60f8">
<serial>G0002340150281214</serial>
<dsmrmain id="17a4e31e9e474644a1ee71d3d1a0d2e2"/>
</dsmrgas>
</protocols>
</module>
<module id="1c625a8dd0ae4040ae2611966f3c650b">
<vendor_name>Xemex</vendor_name>
<vendor_model>XMX5LGBBFG1009008183</vendor_model>
<hardware_version/>
<firmware_version/>
<created_date>2016-11-26T16:38:30.151+01:00</created_date>
<modified_date>2016-11-26T20:10:48.365+01:00</modified_date>
<deleted_date/>
<services>
<electricity_interval_meter id="dd73e5aa231a4392a44be6f43961cab6">
<measurement log_date="2016-11-26T20:00:00+01:00" unit="Wh" interval="PT300S" directionality="produced" tariff_indicator="nl_offpeak">0.000</measurement>
<measurement log_date="2016-11-26T20:00:00+01:00" unit="Wh" interval="PT300S" directionality="produced" tariff_indicator="nl_peak">0.000</measurement>
<measurement log_date="2016-11-26T20:00:00+01:00" unit="Wh" interval="PT300S" directionality="consumed" tariff_indicator="nl_offpeak">56.000</measurement>
<measurement log_date="2016-11-26T20:00:00+01:00" unit="Wh" interval="PT300S" directionality="consumed" tariff_indicator="nl_peak">0.000</measurement>
</electricity_interval_meter>
<electricity_point_meter id="7f85e92215464695a8e3d98a63b60274">
<measurement log_date="2016-11-26T20:10:51+01:00" unit="W" directionality="produced">0.000</measurement>
<measurement log_date="2016-11-26T20:10:51+01:00" unit="W" directionality="consumed">675.000</measurement>
</electricity_point_meter>
<electricity_cumulative_meter id="868ae6678b6a4ef7b3205ac4b4d98054">
<measurement log_date="2016-11-26T20:05:00+01:00" unit="Wh" directionality="produced" tariff_indicator="nl_offpeak">0.000</measurement>
<measurement log_date="2016-11-26T20:05:00+01:00" unit="Wh" directionality="produced" tariff_indicator="nl_peak">0.000</measurement>
<measurement log_date="2016-11-26T20:05:00+01:00" unit="Wh" directionality="consumed" tariff_indicator="nl_offpeak">2148353.000</measurement>
<measurement log_date="2016-11-26T20:05:00+01:00" unit="Wh" directionality="consumed" tariff_indicator="nl_peak">2435586.000</measurement>
</electricity_cumulative_meter>
</services>
<protocols>
<dsmrmain id="17a4e31e9e474644a1ee71d3d1a0d2e2">
<serial>E0030003017330515</serial>
<dsmrmbuses>
<dsmrgas id="cd27a7eb09904168a5d43ae5c0ec60f8"/>
</dsmrmbuses>
</dsmrmain>
</protocols>
</module>
</modules>
```

**Comment by gruijter** [comment]
doh, still not with the formatting I need....

**Comment by StraDijk** [comment]
[modules.zip](https://github.com/gruijter/com.plugwise.smile/files/614403/modules.zip)

**Comment by gruijter** [comment]
got it!
